name: End-to-end tests in Next.js
on:
  pull_request:
    paths:
      - 'src/**'
      - 'cypress/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies root dir â¬‡ï¸
        run: npm install
      - name: Install dependencies next-app dir â¬‡ï¸
        run: npm install
        working-directory: ./cypress/pages/next-app
      - name: Build lib ğŸ”¨
        run: npm run build
      - name: Start server ğŸš€
        run: npm run dev
        working-directory: ./cypress/pages/next-app
      - name: Run Cypress
        run: ./node_modules/.bin/cypress run --spec "cypress/e2e/nextjs/**/*"
